Fix PR678: Use the 4th argument to CHECK_PROGRAM_SANITY in order to turn a failed sanity check into a warning instead of an error.
llvm-svn: 24932

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19287,12 +19287,18 @@ if test "$?" -eq 0 -a -x "$sanity_path" ; then
   if test -z "$sanity" ; then
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-    { { echo "$as_me:$LINENO: error: Program f95 failed to pass sanity check." >&5
+    if test "1" -eq 1 ; then
+      { echo "$as_me:$LINENO: WARNING: Program f95 failed to pass sanity check." >&5
+echo "$as_me: WARNING: Program f95 failed to pass sanity check." >&2;}
+    else
+      { { echo "$as_me:$LINENO: error: Program f95 failed to pass sanity check." >&5
 echo "$as_me: error: Program f95 failed to pass sanity check." >&2;}
    { (exit 1); exit 1; }; }
-  fi
-  echo "$as_me:$LINENO: result: yes" >&5
+    fi
+  else
+    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+  fi
 else
   echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
